import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState,useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

 
  
  return (

    
    <>

      
      <Head>
        <title>Blog Vista</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div className={styles.sections} style={{ display: 'flex', justifyContent: 'space-between' }}>
          <div className={styles.collage} style={{width:'50%',alignItems:'center',marginLeft:'70px',marginTop:'20px'}}>
            {/* collage of images */}
<Image className={styles.coderimg} src="/Coder.jpeg" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/woman-coding.jpg" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/programmer_cmd_line.jpg" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/img1.jpg" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/img2.jpg" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/img4.jpg" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/img5.webp" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/img6.jpg" alt="image loading..." width={180} height={160}/>
<Image className={styles.coderimg} src="/img8.jpg" alt="image loading..." width={180} height={160}/>


          </div>

          <div className={styles.intro} style={{width:'50%'}}>
            {/* title and gotoline */}
            <h1  style={{fontSize:'50px',fontFamily:'Roboto',color:'white',textAlign:'center',fontSize:'80px',marginTop:'120px'}}>Blog Vista</h1>



<h2 style={{marginBottom:'20px',textAlign:'center',color:'white',fontSize:'30px',marginLeft:'10px'}}>Embark on a Journey Through Code: Your Ultimate Tech Safari</h2>
          </div>
      
        </div>
        
       
        
    
    </>
  );
}
